create schema if not exists savis_api;

create table savis_api.activity_rates (
    id bigint generated by default as identity primary key,
    activity_type varchar(255) not null unique,
    hourly_rate_amount numeric(38, 2) not null,
    hourly_rate_currency varchar(255) not null
);

create table savis_api.boms (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    name varchar(255) not null unique,
    description varchar(255) not null,
    image_url varchar(255) not null,
    instructions varchar(255),
    type varchar(255),
    quantity double precision not null,
    unit varchar(255) not null
);

create table savis_api.bom_components (
    id bigint generated by default as identity primary key,
    bom_id bigint not null references savis_api.boms(id),
    component_name varchar(255),
    quantity double precision not null,
    unit varchar(255),
    selected_offer_id uuid
);

create table savis_api.bom_activities (
    id bigint generated by default as identity primary key,
    bom_id bigint not null references savis_api.boms(id),
    type varchar(255) not null,
    minutes integer not null,
    sequence integer not null
);

create table savis_api.catalog_product_categories (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    code varchar(255) not null unique,
    name varchar(255) not null,
    active boolean not null,
    display_order integer not null
);

create table savis_api.catalog_product_choice_groups (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    label varchar(255) not null,
    required boolean not null
);

create table savis_api.catalog_products (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    code varchar(255) not null unique,
    slug varchar(255) not null unique,
    name varchar(255) not null,
    description text not null,
    product_type varchar(255) not null,
    category_public_id uuid not null,
    base_price_amount numeric(14, 2) not null,
    base_price_currency varchar(3) not null,
    target_margin_rate numeric(7, 6) not null,
    unit_label varchar(255) not null,
    image_url text not null,
    gallery jsonb not null,
    availability_note varchar(255) not null,
    available boolean not null,
    published boolean not null,
    display_order integer not null,
    choice_group_id bigint unique references savis_api.catalog_product_choice_groups(id)
);

create table savis_api.catalog_product_boms (
    id bigint generated by default as identity primary key,
    product_id bigint not null references savis_api.catalog_products(id),
    public_id uuid not null unique,
    bom_id uuid not null,
    quantity numeric(14, 6) not null,
    display_order integer not null
);

create table savis_api.catalog_product_purchase_modes (
    id bigint generated by default as identity primary key,
    product_id bigint not null references savis_api.catalog_products(id),
    public_id uuid not null unique,
    code varchar(255) not null,
    label varchar(255) not null,
    quantity integer not null,
    price_amount numeric(14, 2) not null,
    price_currency varchar(3) not null,
    allocation_type varchar(255) not null,
    active boolean not null,
    display_order integer not null
);

create table savis_api.catalog_product_choice_options (
    id bigint generated by default as identity primary key,
    choice_group_id bigint not null references savis_api.catalog_product_choice_groups(id),
    public_id uuid not null unique,
    code varchar(255) not null,
    name varchar(255) not null,
    bom_id uuid,
    active boolean not null,
    display_order integer not null
);

create table savis_api.catalog_product_ingredient_options (
    id bigint generated by default as identity primary key,
    product_id bigint not null references savis_api.catalog_products(id),
    public_id uuid not null unique,
    code varchar(255) not null,
    name varchar(255) not null,
    bom_id uuid,
    default_quantity integer not null,
    min_quantity integer not null,
    max_quantity integer not null,
    extra_price_amount numeric(14, 2) not null,
    extra_price_currency varchar(3) not null,
    active boolean not null,
    display_order integer not null
);

create table savis_api.offers (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    external_id varchar(255) not null,
    url varchar(255),
    component_name varchar(255) not null,
    brand varchar(255),
    label varchar(255),
    image_url varchar(255),
    price_amount numeric(38, 2),
    price_currency varchar(255),
    package_size_value double precision,
    package_size_unit varchar(255),
    provider_name varchar(255),
    provider_identifier varchar(255),
    provider_site varchar(255),
    provider_address varchar(255),
    last_seen timestamp,
    status varchar(255) not null
);

create table savis_api.event_publication (
    completion_attempts integer not null,
    completion_date timestamp with time zone,
    last_resubmission_date timestamp with time zone,
    publication_date timestamp with time zone not null,
    id uuid primary key,
    event_type varchar(255) not null,
    listener_id varchar(255) not null,
    serialized_event varchar(255) not null,
    status varchar(255)
);

create index idx_bom_components_bom_id on savis_api.bom_components(bom_id);
create index idx_bom_activities_bom_id on savis_api.bom_activities(bom_id);
create index idx_catalog_products_display on savis_api.catalog_products(display_order, name);
create index idx_catalog_products_published on savis_api.catalog_products(published, display_order, name);
create index idx_catalog_product_boms_product on savis_api.catalog_product_boms(product_id);
create index idx_catalog_purchase_modes_product on savis_api.catalog_product_purchase_modes(product_id);
create index idx_catalog_choice_options_group on savis_api.catalog_product_choice_options(choice_group_id);
create index idx_catalog_ingredients_product on savis_api.catalog_product_ingredient_options(product_id);
create index idx_offers_lookup on savis_api.offers(external_id, provider_identifier);
create index idx_offers_search on savis_api.offers(status, component_name, price_amount);
